export interface DemoProps {
  textareaValue: string
  onTextareaChange: (value: string) => void
}

export const demoCopies = {
  pageTitle: "Component demo",
  pageDescription: "Gallery of design-system primitives used in the financial advisor app.",
  sectionButtons: "Buttons",
  sectionFeedback: "Feedback",
  sectionOverlays: "Overlays",
  sectionDataDisplay: "Data display",
  sectionInputs: "Inputs",
  sectionLayout: "Layout",
  primaryButton: "Primary",
  secondaryButton: "Secondary",
  outlineButton: "Outline",
  ghostButton: "Ghost",
  destructiveButton: "Destructive",
  iconButtonLabel: "Settings",
  badgeDefault: "Default",
  badgeSecondary: "Secondary",
  badgeOutline: "Outline",
  badgeDestructive: "Alert",
  avatarFallback: "FA",
  tooltipTrigger: "Hover me",
  tooltipContent: "Tooltip content",
  dropdownTrigger: "Open menu",
  dropdownLabel: "Actions",
  dropdownItemProfile: "Profile",
  dropdownItemBilling: "Billing",
  dropdownItemLogout: "Log out",
  dialogTrigger: "Open dialog",
  dialogTitle: "Confirm action",
  dialogDescription: "This dialog demonstrates the Dialog primitive.",
  dialogClose: "Close",
  sheetTrigger: "Open sheet",
  sheetTitle: "Sheet panel",
  sheetDescription: "Side panel content for secondary flows.",
  popoverTrigger: "Open popover",
  popoverTitle: "Quick tip",
  popoverDescription: "Popover content for lightweight contextual info.",
  separatorLabel: "Separator",
  skeletonLabel: "Loading placeholders",
  spinnerLabel: "Loading",
  alertTitle: "Heads up",
  alertDescription: "You can use Alert for important status messages.",
  alertDestructiveTitle: "Something went wrong",
  alertDestructiveDescription: "Check your connection and try again.",
  scrollAreaTitle: "Scroll area",
  scrollAreaItem: "List item",
  textareaLabel: "Message",
  textareaPlaceholder: "Type a message for the advisor…",
} as const
